---
- hosts: localhost
  tasks: 
    - name: Install homebrew
      include_role: 
        name: geerlingguy.mac.homebrew

    - name: Make sure homebrew bin is in path
      ansible.builtin.lineinfile: 
        path: /etc/paths
        state: present
        line: '/opt/homebrew/bin'
      become: true
      become_user: root

    - name: 'add custom homebrew repos'
      community.general.homebrew_tap: 
        name: [
            adoptopenjdk/openjdk,
            shopify/shopify,
            heroku/brew,
            homebrew/cask-versions,
            homebrew/cask-fonts,
            thoughtbot/formulae,
            weaveworks/tap,
            blacktop/tap,
          ]

    - name: Install core packages via brew casks
      community.general.homebrew_cask: 
        name: "{{ item }}"
      ignore_errors: yes
      with_items: 
        - adobe-creative-cloud
        - android-sdk
        - android-studio
        - apparency 
        - arc
        - backblaze
        - bartender
        - beeper
        - blender
        - cleanmymac
        - dash
        - discord
        - docker
        - figma
        - fleet
        - google-chrome
        - google-cloud-sdk
        - google-drive
        - intellij-idea-ce
        - kindle
        - logi-options-plus
        - monitorcontrol
        - ngrok
        - notunes
        - qlcolorcode
        - qlimagesize
        - qlmarkdown
        - qlstephen
        - qlvideo
        - quicklook-csv
        - quicklook-json
        - quicklookase
        - raycast
        - signal
        - slack
        - surfshark
        - suspicious-package 
        - tableplus
        - telegram
        - ticktick
        - visual-studio-code
        - vlc
        - warp
        - zoom

    - name: "Install homebrew packages"
      community.general.homebrew: 
        name: [
            'autoconf',
            'automake',
            'aws-iam-authenticator',
            'awscli',
            'bfg',
            'coreutils',
            'curl',
            'direnv',
            'awscli',
            'azure-cli',
            'bitwarden-cli',
            'chezmoi',
            'lporg',
            'exercism',
            'fnm',
            'gh',
            'go',
            'kubernetes-cli',
            'lefthook',
            'pnpm',
            'poetry',
            'rustup-init',
            'sheldon',
            'shopify-cli',
            'starship',
            'opentofu',
            'tmux',
            'tree',
            'tree-sitter',
            'uru',
            'fzf',
            'htop',
            'kubectx',
            'kubernetes-cli',
            'kubernetes-helm',
            'libtool',
            'libxslt',
            'libyaml',
            'mas',
            'openssl' ,
            'pkg-config',
            'postgresql',
            'rcm',
            'readline',
            'redis',
            'sqlite3',
            'tmux',
            'unixodbc',
            'unzip',
            'vim',
            'watchman',
            'xz',
            'yarn',
            'zlib',
            'zsh',
          ]
        state: present
        update_homebrew: yes

    - name: ensure fonts directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.fonts"
        state: directory

    - name: Hack exists
      shell: "ls {{ lookup('env', 'HOME') }}/.fonts/Hack*Nerd*Font*Complete*"
      register: hack_exists
      ignore_errors: yes

    - name: Download Hack
      when: hack_exists is failed
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
        dest: "{{ lookup('env', 'HOME') }}/.fonts/"
        remote_src: yes

    - name: "Install from Mac app store"
      shell: mas install {{ item }}
      with_items: 
        - 497799835  # xcode
        - 1352778147 # bitwarden
        - 1446377255 # menu-world-time
        - 937984704  # amphetamine
        - 571213070  # davinci resolve

    - name: Get the path to ZSH
      become: false
      local_action: command which zsh
      register: zsh_path

    - name: "Ensure homebrew zsh is in allowed shells"
      lineinfile: 
        path: /etc/shells
        line: "{{ zsh_path.stdout }}"
      become: true

    - name: Set ZSH as the default shell
      shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
      become: true

    - name: "Create a default ZSH configuration"
      template: 
        src: templates/.zshrc.j2
        dest: /Users/{{ lookup('env', 'USER') }}/.zshrc
        owner: "{{ lookup('env', 'USER') }}"
        force: yes

    - name: Create a default VSCode configuration
      template: 
        src: templates/vscode-settings.json.j2
        dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Code/User/settings.json
        owner: "{{ lookup('env', 'USER') }}"
        force: yes

    - name: Create a default VSCode keybinding configuration
      template: 
        src: templates/vscode-keybindings.json.j2
        dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Code/User/keybindings.json
        owner: "{{ lookup('env', 'USER') }}"
        force: yes

    # Add something which ensures path is set here
    - name: Install VSCode extensions
      shell: code --install-extension {{ item }}
      with_items: 
        - apollographql.vscode-apollo
        - bradlc.vscode-tailwindcss
        - castwide.solargraph
        - clinyong.vscode-css-modules
        - jakebecker.elixir-ls
        - kaiwood.endwise
        - karunamurti.haml
        - ms-vscode-remote.vscode-remote-extensionpack
        - ms-vscode.vscode-typescript-tslint-plugin
        - msjsdiag.debugger-for-chrome
        - rebornix.ruby
        - richie5um2.vscode-sort-json
        - Tyriar.sort-lines
        - wholroyd.jinja
        - wingrunr21.vscode-ruby
        - xabikos.javascriptsnippets
        - streetsidesoftware.code-spell-checker
        - fabiospampinato.vscode-todo-plus

    - name: Setting languages
      community.general.osx_defaults: 
        key: AppleLanguages
        type: array
        value: 
          - en
          - de

    - name: Use touch id for sudo
      community.general.osx_defaults: 
        key: "auth sufficient pam_tid.so"
        type: string
        value: "auth sufficient pam_tid.so"

    - name: Show finder as columns by default
      community.general.osx_defaults: 
        key: FXPreferredViewStyle
        type: string
        value: clmv

    - name: Show hidden files in finder
      community.general.osx_defaults: 
        key: AppleShowAllFiles
        type: bool
        value: true

    - name: Show path bar in finder
      community.general.osx_defaults: 
        key: ShowPathbar
        type: bool
        value: true

    - name: Show percentage in battery
      community.general.osx_defaults: 
        key: ShowPercent
        type: bool
        value: true

    - name: Show battery percentage in menu bar
      community.general.osx_defaults: 
        key: "com.apple.menuextra.battery"
        domain: "ShowPercent"
        type: bool
        value: true

    - name: Disable tip click in trackpad
      community.general.osx_defaults: 
        key: "com.apple.driver.AppleBluetoothMultitouch.trackpad"
        domain: "Clicking"
        type: bool
        value: false

    - name: Disable tap to drag on trackpad
      community.general.osx_defaults: 
        key: "com.apple.AppleMultitouchTrackpad"
        domain: "Dragging"
        type: bool
        value: false

    - name: Disable force click on trackpad
      community.general.osx_defaults: 
        key: "com.apple.AppleMultitouchTrackpad.ForceClick"
        type: bool
        value: false

    - name: Deactivate rearrange spaces based on most recent use
      community.general.osx_defaults: 
        key: "com.apple.dock.mru-spaces"
        type: bool
        value: false

    - name: Don't show recent applications in dock
      community.general.osx_defaults: 
        key: "com.apple.dock.show-recents"
        type: bool
        value: false

    - name: Remove all default apps from dock
      community.general.osx_defaults: 
        key: "com.apple.dock persistent-apps"
        type: array
        value: []

    - name: Open new finder windows in home directory
      community.general.osx_defaults: 
        key: "com.apple.finder NewWindowTarget"
        type: string
        value: PfHm

    - name: Remove recent from finder sidebar
      community.general.osx_defaults: 
        key: "com.apple.finder ShowRecentTags"
        type: bool
        value: false

    - name: remove all tags from finder sidebar
      community.general.osx_defaults: 
        key: "com.apple.finder SidebarTagsSctionDisclosedState"
        type: bool
        value: false

    - name: Rearrange favorites list 
      community.general.osx_defaults: 
        key: "com.apple.LSSharedFileList.FavoriteItems"
        type: array
        value: 
          - "com.apple.finder.GoToHome"
          - "com.apple.finder.GoToComputer"
          - "File: ///Users/{{ lookup('env', 'USER') }}/Projects/"
          - "com.apple.finder.GoToiCloudDrive"
          - "com.apple.finder.GoToDownloads"
          - "com.apple.finder.GoToDocuments"
          - "com.apple.finder.GoToApplications"
          - "com.apple.finder.GoToAirDrop"

    - name: Group finder items by type by default
      community.general.osx_defaults: 
        key: "com.apple.finder FXPreferredGroupBy"
        type: string
        value: "Kind"

    - name: Sort finder items by name by default
      community.general.osx_defaults: 
        key: "com.apple.finder FXPreferredSortBy"
        type: string
        value: "Name"

    - name: Deactivate spelling correction
      community.general.osx_defaults: 
        key: "NSAutomaticSpellingCorrectionEnabled"
        type: bool
        value: false

    - name: Deactivate automatic capitalization
      community.general.osx_defaults: 
        key: "NSAutomaticCapitalizationEnabled"
        type: bool
        value: false
    
    - name: Deactivate automatic period substitution
      community.general.osx_defaults: 
        key: "NSAutomaticPeriodSubstitutionEnabled"
        type: bool
        value: false

    - name: Deactivate smart dashes
      community.general.osx_defaults: 
        key: "NSAutomaticDashSubstitutionEnabled"
        type: bool
        value: false

    - name: Deactivate smart quotes
      community.general.osx_defaults: 
        key: "NSAutomaticQuoteSubstitutionEnabled"
        type: bool
        value: false

    - name: Initial key repeat delay
      community.general.osx_defaults: 
        key: "InitialKeyRepeat"
        type: float
        value: 15

    - name: Key repeat rate
      community.general.osx_defaults: 
        key: "KeyRepeat"
        type: float
        value: 2

    - name: German date and time format
      community.general.osx_defaults: 
        key: "AppleLocale"
        type: string
        value: "de_DE@currency=EUR"

    - name: 24 hour time format
      community.general.osx_defaults: 
        key: "AppleICUForce24HourTime"
        type: bool
        value: true

    - name: Do not show recent applications in dock
      community.general.osx_defaults: 
        key: "com.apple.dock show-recents"
        type: bool
        value: false

    - name: Set system theme to dark
      community.general.osx_defaults: 
        key: "AppleInterfaceStyle"
        type: string
        value: "Dark"

    - name: Set measurements to metric
      community.general.osx_defaults: 
        key: "AppleMeasurementUnits"
        type: string
        value: "Centimeters"

    - name: Set temperature to celsius
      community.general.osx_defaults: 
        key: "AppleTemperatureUnit"
        type: string
        value: "Celsius"

    - name: Set first day of week to monday
      community.general.osx_defaults: 
        key: "AppleFirstWeekday"
        type: int
        value: 1

    - name: Expand save panel by default
      community.general.osx_defaults: 
        key: "NSNavPanelExpandedStateForSaveMode"
        type: bool
        value: true

    - name: Expand print panel by default
      community.general.osx_defaults: 
        key: "PMPrintingExpandedStateForPrint"
        type: bool
        value: true

    - name: Set bluetooth audio to Apple Bitpool Min (editable)
      community.general.osx_defaults: 
        key: "com.apple.BluetoothAudioAgent"
        domain: "Apple Bitpool Min (editable)"
        type: int
        value: 40

    - name: Show external harddrives on desktop
      community.general.osx_defaults: 
        key: "com.apple.finder ShowExternalHardDrivesOnDesktop"
        type: bool
        value: true

    - name: Do not show network drives on desktop
      community.general.osx_defaults: 
        key: "com.apple.finder ShowMountedServersOnDesktop"
        type: bool
        value: false

    - name: Do not show removable media on desktop
      community.general.osx_defaults: 
        key: "com.apple.finder ShowRemovableMediaOnDesktop"
        type: bool
        value: false

    - name: Speed up mission control animations
      community.general.osx_defaults: 
        key: "com.apple.dock expose-animation-duration"
        type: float
        value: 0.1

    - name: remove shared directory from icloud sidebar
      community.general.osx_defaults: 
        key: "com.apple.finder SidebariCloudDesktopShow"
        type: bool
        value: false

    - name: Move icloud folder to favorites in finder sidebar
      community.general.osx_defaults: 
        key: "com.apple.finder SidebariCloudDesktopShow"
        type: bool
        value: false

    - name: Don't warn before emptying trash
      community.general.osx_defaults: 
        key: "com.apple.finder WarnOnEmptyTrash"
        type: bool
        value: false


